### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Tensor'

### ISSUE THREAD

**Issue by quentinzh** [yfwang2021/ITFR#1]
Hello author, thank you very much for sharing your code. I encountered an error while running it and I'm unable to resolve it. Could you please provide some assistance?

The error occurred in the ITFR.py file, as shown in the figure:
![image](https://github.com/user-attachments/assets/ddffea3d-2f91-408b-8365-c8619e60a6c2)

The error message is as follows:
![image](https://github.com/user-attachments/assets/7ab30230-a138-44c0-a4c3-ef299ab7562a)

How can this issue be resolved? I am very grateful for your assistance🙏🌹

**Comment by yfwang2021** [comment]
Thank you for your attention to our work!

The code runs properly in my local environment, so I suspect the issue might be caused by an inconsistency in the environment, which prevents `params[pid].grad` from being correctly initialized. I suggest checking if your current environment matches the configurations specified in `requirements.txt`.

If you still wish to run the code in your current environment, you could consider modifying the code as follows:

```python
if params[pid].grad is None:
    params[pid].grad = torch.zeros_like(all_grads[li][pid])
params[pid].grad += model.rwt[li] * all_grads[li][pid]
```

I hope these suggestions help resolve your issue!
